(function () {
  const NT2 = window.NT2 = window.NT2 || {};

  const dict = {
    lo: {
      'nav.dashboard': 'ໜ້າຫຼັກ',
      'nav.teachers': 'ຄູອາຈານ',
      'nav.students': 'ນັກຮຽນ',
      'nav.scores': 'ຄະແນນ',
      'nav.attendance': 'ຕິດຕາມການມາຮຽນ',
      'nav.schedule': 'ຕາຕະລາງ',
      'nav.classes': 'ຊັ້ນຮຽນ',
      'page.dashboard': 'ໜ້າຫຼັກ',
      'page.academic_year': 'ສົກຮຽນ',
      'page.teachers': 'ຄູອາຈານ',
      'page.students': 'ນັກຮຽນ',
      'page.scores': 'ຄະແນນ',
      'page.attendance': 'ຕິດຕາມການມາຮຽນ',
      'page.schedule': 'ຕາຕະລາງ',
      'page.classes': 'ຊັ້ນຮຽນ',
      'header.refresh': 'ໂຫຼດຂໍ້ມູນໃໝ່ຈາກ Google Sheet',
      'header.theme': 'ສະຫຼັບໂໝດສີ',
      'header.lang': 'ປ່ຽນພາສາ',
      'header.year': 'ສົກຮຽນ',
      'lang.label': 'ລາວ',
      'login.login': 'ເຂົ້າສູ່ລະບົບ',
      'login.logout': 'ອອກຈາກລະບົບ',
      'login.username': 'ຊື່ຜູ້ໃຊ້',
      'login.password': 'ລະຫັດຜ່ານ',
      'login.userPh': 'ໃສ່ຊື່ຜູ້ໃຊ້',
      'login.passPh': 'ໃສ່ລະຫັດຜ່ານ',
      'login.cancel': 'ຍົກເລີກ',
      'login.success': 'ເຂົ້າສູ່ລະບົບສຳເລັດ',
      'login.loggedOut': 'ອອກຈາກລະບົບແລ້ວ',
      'login.invalid': 'ຊື່ຜູ້ໃຊ້ ຫຼື ລະຫັດຜ່ານບໍ່ຖືກຕ້ອງ!',
      'theme.auto': 'ໂໝດອັດຕະໂນມັດ',
      'theme.light': 'ໂໝດສະຫວ່າງ',
      'theme.dark': 'ໂໝດມືດ',
      'zoom.no_image': 'ບໍ່ມີຮູບພາບທີ່ຈະຂະຫຍາຍ',
      'zoom.close': 'ປິດ (ESC)',
      'zoom.image': 'ຮູບ',
      'zoom.load_error': 'ບໍ່ສາມາດໂຫລດຮູບໄດ້',
      'zoom.tip': 'ກົດບ່ອນຫວ່າງ ຫຼື ປຸ່ມປິດ ເພື່ອອອກ',
      'months': ['ມັງກອນ','ກຸມພາ','ມີນາ','ເມສາ','ພຶດສະພາ','ມິຖຸນາ','ກໍລະກົດ','ສິງຫາ','ກັນຍາ','ຕຸລາ','ພະຈິກ','ທັນວາ'],
      'loading': 'ກຳລັງໂຫຼດຂໍ້ມູນ...',
      'sync.loading': 'ກຳລັງໂຫຼດ...',
      'sync.empty': 'ບໍ່ມີຂໍ້ມູນ',
      'sync.sample': 'ບໍ່ມີຂໍ້ມູນ',
      'sync.prefix': 'Google Sheet •',
      'notice.sample': 'ກຳລັງໃຊ້ຂໍ້ມູນຕົວຢ່າງ — ກະລຸນາ Publish Google Sheet ເພື່ອດຶງຂໍ້ມູນຈິງ',
      'toast.refreshed': 'ຂໍ້ມູນອັບເດດຈາກ Google Sheet ແລ້ວ!',
      'toast.saving_sheet': 'ກຳລັງບັນທຶກໃສ່ Google Sheet...',
      'toast.saving': 'ກຳລັງບັນທຶກລົງ Google Sheet...',
      'toast.updating': 'ກຳລັງບັນທຶກການແກ້ໄຂໃສ່ Google Sheet...',
      'toast.deleting': 'ກຳລັງລຶບ...',
      'toast.deleting_data': 'ກຳລັງລຶບຂໍ້ມູນອອກຈາກ Google Sheet...',
      'toast.save_error': 'ບໍ່ສາມາດບັນທຶກໄດ້ — ກະລຸນາກວດສອບ Google Script',
      'toast.enter_title': 'ກະລຸນາໃສ່ຫົວຂໍ້ແຈ້ງການ',
      'toast.enter_teacher_name': 'ກະລຸນາໃສ່ຊື່ຄູອາຈານ',
      'toast.enter_student_name': 'ກະລຸນາໃສ່ຊື່ນັກຮຽນ',
      'toast.added_ann': 'ເພີ່ມແຈ້ງການສຳເລັດ!',
      'toast.updated_ann': 'ແກ້ໄຂແຈ້ງການສຳເລັດ!',
      'toast.deleted_ann': 'ລຶບແຈ້ງການສຳເລັດ!',
      'toast.added_teacher': 'ເພີ່ມຂໍ້ມູນຄູອາຈານສຳເລັດ!',
      'toast.updated_teacher': 'ແກ້ໄຂຂໍ້ມູນຄູອາຈານສຳເລັດ!',
      'toast.deleted_teacher': 'ລຶບຂໍ້ມູນຄູອາຈານສຳເລັດ!',
      'toast.added_student': 'ເພີ່ມຂໍ້ມູນນັກຮຽນສຳເລັດ!',
      'toast.updated_student': 'ແກ້ໄຂຂໍ້ມູນນັກຮຽນສຳເລັດ!',
      'toast.deleted_student': 'ລຶບຂໍ້ມູນນັກຮຽນສຳເລັດ!',
      'noLink.scores': 'ຍັງບໍ່ທັນໄດ້ໃສ່ລິ້ງ — ກະລຸນາໃສ່ URL ໃນ Google Sheet tab "scores_links"',
      'noLink.attendance': 'ຍັງບໍ່ທັນໄດ້ໃສ່ລິ້ງ — ກະລຸນາໃສ່ URL ໃນ Google Sheet (ແຖວ 3)',
      'toast.year_selected': 'ເລືອກສົກຮຽນ',
      'confirm.delete': 'ທ່ານຕ້ອງການລຶບ',
      'confirm.q': 'ແທ້ບໍ?',
      'common.add': 'ເພີ່ມ',
      'common.edit': 'ແກ້ໄຂ',
      'common.delete': 'ລຶບ',
      'common.cancel': 'ຍົກເລີກ',
      'common.save': 'ບັນທຶກ',
      'common.save_edit': 'ບັນທຶກການແກ້ໄຂ',
      'common.save_sheet': 'ບັນທຶກລົງ Sheet',
      'common.close': 'ປິດ',
      'common.photo': 'ຮູບ',
      'common.photo_link': 'ຮູບພາບ (Link URL)',
      'common.name_lao_long': 'ຊື່ ແລະ ນາມສະກຸນ (ພາສາລາວ)',
      'common.name_en_long': 'ຊື່ ແລະ ນາມສະກຸນ (ພາສາອັງກິດ)',
      'common.name_lao_th': 'ຊື່ ແລະ ນາມສະກຸນ (ລາວ)',
      'common.name_en_th': 'Name & Surname (EN)',
      'common.position': 'ຕຳແໜ່ງ',
      'common.subject': 'ວິຊາສອນ',
      'common.phone': 'ເບີໂທ',
      'common.class_room': 'ຊັ້ນ/ຫ້ອງ',
      'common.manage': 'ຈັດການ',
      'common.see_photo': 'ກົດເພື່ອເບິ່ງຮູບໃຫຍ່',
      'common.all_class': 'ທຸກຊັ້ນ',
      'common.room': 'ຫ້ອງ',
      'common.saving': 'ກຳລັງບັນທຶກ...',
      'common.no_data': 'ບໍ່ມີຂໍ້ມູນ',

      'dash.title': 'ໜ້າຫຼັກ',
      'dash.live': 'ຂໍ້ມູນ Live',
      'dash.sample': 'ຂໍ້ມູນຕົວຢ່າງ',
      'dash.stat.students': 'ນັກຮຽນທັງໝົດ',
      'dash.stat.teachers': 'ຄູອາຈານທັງໝົດ',
      'dash.stat.classes': 'ຫ້ອງຮຽນທັງໝົດ',
      'dash.stat.ann': 'ແຈ້ງການ',
      'dash.urgent': 'ແຈ້ງການດ່ວນ',
      'dash.normal': 'ແຈ້ງການທົ່ວໄປ',
      'dash.badge.urgent': 'ດ່ວນ',
      'dash.badge.normal': 'ທົ່ວໄປ',
      'dash.no_urgent': 'ບໍ່ມີແຈ້ງການດ່ວນ',
      'dash.no_ann': 'ບໍ່ມີແຈ້ງການ',
      'dash.past': 'ການເຄື່ອນໄຫວຜ່ານມາທີ່ລ່າສຸດ',
      'dash.activity': 'ການເຄື່ອນໄຫວ',

      'modal.add_ann': 'ເພີ່ມແຈ້ງການ / ການເຄື່ອນໄຫວ',
      'modal.edit_ann': 'ແກ້ໄຂແຈ້ງການ / ການເຄື່ອນໄຫວ',
      'modal.date': 'ວັນທີ',
      'modal.type': 'ປະເພດ',
      'modal.title': 'ຫົວຂໍ້',
      'modal.content': 'ເນື້ອໃນ',
      'modal.title_ph': 'ໃສ່ຫົວຂໍ້ແຈ້ງການ',
      'modal.content_ph': 'ໃສ່ເນື້ອໃນແຈ້ງການ',

      'year.current': 'ສົກຮຽນປະຈຸບັນ',
      'year.active': 'ກຳລັງດຳເນີນ',
      'year.history': 'ປະຫວັດສົກຮຽນທັງໝົດ',
      'year.start': 'ວັນເລີ່ມ',
      'year.end': 'ວັນສິ້ນສຸດ',
      'year.status': 'ສະຖານະ',
      'year.note': 'ໝາຍເຫດ',
      'year.empty': 'ບໍ່ມີຂໍ້ມູນສົກຮຽນ — ກະລຸນາໃສ່ຂໍ້ມູນໃນ sheet "academic_year" ໃນ Google Sheet',
      'year.sheet_info': 'ຂໍ້ມູນ Google Sheet',
      'year.sheet_desc': 'ຂໍ້ມູນສົກຮຽນດຶງມາຈາກ Sheet Tab ຊື່',
      'year.col_required': 'ໂຄງສ້າງ column ທີ່ຕ້ອງການ:',
      'year.col_meaning': 'ຄວາມໝາຍ',
      'year.col_example': 'ຕົວຢ່າງ',

      'teach.title_full': 'ຂໍ້ມູນຄູອາຈານ',
      'teach.search': 'ຄົ້ນຫາຊື່, ຕຳແໜ່ງ, ວິຊາ...',
      'teach.add': 'ເພີ່ມຄູອາຈານ',
      'teach.empty': 'ບໍ່ພົບຂໍ້ມູນຄູອາຈານ',
      'teach.add_title': 'ເພີ່ມຂໍ້ມູນຄູອາຈານ',
      'teach.edit_title': 'ແກ້ໄຂຂໍ້ມູນຄູອາຈານ',

      'stu.title_full': 'ຂໍ້ມູນນັກຮຽນ',
      'stu.search': 'ຄົ້ນຫາຊື່, ຫ້ອງ...',
      'stu.opt_kinder': 'ອະນຸບານ',
      'stu.opt_primary': 'ປະຖົມ',
      'stu.opt_secondary': 'ມັດທະຍົມ',
      'stu.total_label': 'ນັກຮຽນທັງໝົດ',
      'stu.total_unit': 'ຄົນ',
      'stu.empty': 'ບໍ່ພົບຂໍ້ມູນນັກຮຽນ',
      'stu.add': 'ເພີ່ມນັກຮຽນ',
      'stu.add_title': 'ເພີ່ມຂໍ້ມູນນັກຮຽນ',
      'stu.edit_title': 'ແກ້ໄຂຂໍ້ມູນນັກຮຽນ',

      'score.title_full': 'ລະບົບຄະແນນ',
      'score.rules': 'ກົດລະບຽບຕັດຄະແນນ',
      'score.view': 'ເບິ່ງຄະແນນ ›',
      'score.noLink': 'ຍັງບໍ່ທັນມີລິ້ງ',
      'score.edit_links': 'ແກ້ໄຂລິ້ງ',
      'score.kinder': 'ອະນຸບານ',
      'score.primary': 'ປະຖົມສຶກສາ',
      'score.secondary': 'ມັດທະຍົມສຶກສາ',
      'score.class1': 'ອະນຸບານ',
      'score.class2': 'ປະຖົມ',
      'score.class3': 'ມັດທະຍົມ',

      'att.title_full': 'ຕິດຕາມການມາຮຽນ',
      'att.view': 'ເບິ່ງການມາຮຽນ ›',
      'att.noLink': 'ຍັງບໍ່ທັນມີລິ້ງ',
      'att.edit_links': 'ແກ້ໄຂລິ້ງ',

      'sched.title_full': 'ຕາຕະລາງ',
      'sched.study': 'ຕາຕະລາງຮຽນ (ນັກຮຽນ)',
      'sched.teach': 'ຕາຕະລາງສອນ (ຄູອາຈານ)',
      'sched.empty': 'ບໍ່ພົບຂໍ້ມູນຕາຕະລາງ',
      'sched.break': 'ພັກ',

      'class.title_full': 'ຊັ້ນຮຽນທັງໝົດ',
      'class.kinder': 'ອະນຸບານສຶກສາ',
      'class.primary': 'ປະຖົມສຶກສາ',
      'class.secondary': 'ມັດທະຍົມສຶກສາ',
      'class.students': 'ນັກຮຽນ',
      'class.unit': 'ຄົນ',
      'class.empty': 'ບໍ່ມີຂໍ້ມູນນັກຮຽນໃນຫ້ອງນີ້',
      'class.modal_title': 'ນັກຮຽນ',

      'rules.title': 'ກົດລະບຽບການຕັດຄະແນນ',
      'rules.level': 'ລະດັບ',
      'rules.score': 'ຄະແນນ',
      'rules.meaning': 'ໝາຍຄວາມວ່າ',
      'rules.excellent': 'ດີເລີດ',
      'rules.excellent_m': 'ຜ່ານດີທີ່ສຸດ',
      'rules.good': 'ດີ',
      'rules.good_m': 'ຜ່ານດີ',
      'rules.average': 'ປານກາງ',
      'rules.average_m': 'ຜ່ານ',
      'rules.weak': 'ອ່ອນ',
      'rules.weak_m': 'ຜ່ານ (ມີເງື່ອນໄຂ)',
      'rules.fail': 'ຕົກ',
      'rules.fail_m': 'ບໍ່ຜ່ານ'
    },
    en: {
      'nav.dashboard': 'Dashboard',
      'nav.teachers': 'Teachers',
      'nav.students': 'Students',
      'nav.scores': 'Scores',
      'nav.attendance': 'Attendance',
      'nav.schedule': 'Schedule',
      'nav.classes': 'Classes',
      'page.dashboard': 'Dashboard',
      'page.academic_year': 'Academic Year',
      'page.teachers': 'Teachers',
      'page.students': 'Students',
      'page.scores': 'Scores',
      'page.attendance': 'Attendance',
      'page.schedule': 'Schedule',
      'page.classes': 'Classes',
      'header.refresh': 'Reload data from Google Sheet',
      'header.theme': 'Toggle color theme',
      'header.lang': 'Change language',
      'header.year': 'Academic Year',
      'lang.label': 'EN',
      'login.login': 'Login',
      'login.logout': 'Logout',
      'login.username': 'Username',
      'login.password': 'Password',
      'login.userPh': 'Enter username',
      'login.passPh': 'Enter password',
      'login.cancel': 'Cancel',
      'login.success': 'Logged in successfully',
      'login.loggedOut': 'Logged out',
      'login.invalid': 'Invalid username or password!',
      'theme.auto': 'Auto mode',
      'theme.light': 'Light mode',
      'theme.dark': 'Dark mode',
      'zoom.no_image': 'No image to zoom',
      'zoom.close': 'Close (ESC)',
      'zoom.image': 'Photo',
      'zoom.load_error': 'Could not load image',
      'zoom.tip': 'Click empty area or close button to exit',
      'months': ['January','February','March','April','May','June','July','August','September','October','November','December'],
      'loading': 'Loading data...',
      'sync.loading': 'Loading...',
      'sync.empty': 'No data available',
      'sync.sample': 'No data available',
      'sync.prefix': 'Google Sheet •',
      'notice.sample': 'Currently using sample data — please Publish the Google Sheet to load live data',
      'toast.refreshed': 'Data updated from Google Sheet!',
      'toast.saving_sheet': 'Saving to Google Sheet...',
      'toast.saving': 'Saving to Google Sheet...',
      'toast.updating': 'Saving edits to Google Sheet...',
      'toast.deleting': 'Deleting...',
      'toast.deleting_data': 'Deleting data from Google Sheet...',
      'toast.save_error': 'Could not save — please check Google Script',
      'toast.enter_title': 'Please enter an announcement title',
      'toast.enter_teacher_name': 'Please enter a teacher name',
      'toast.enter_student_name': 'Please enter a student name',
      'toast.added_ann': 'Announcement added!',
      'toast.updated_ann': 'Announcement updated!',
      'toast.deleted_ann': 'Announcement deleted!',
      'toast.added_teacher': 'Teacher added!',
      'toast.updated_teacher': 'Teacher updated!',
      'toast.deleted_teacher': 'Teacher deleted!',
      'toast.added_student': 'Student added!',
      'toast.updated_student': 'Student updated!',
      'toast.deleted_student': 'Student deleted!',
      'noLink.scores': 'No link yet — please add the URL in the "scores_links" Google Sheet tab',
      'noLink.attendance': 'No link yet — please add the URL in Google Sheet (row 3)',
      'toast.year_selected': 'Selected year',
      'confirm.delete': 'Are you sure you want to delete',
      'confirm.q': '?',
      'common.add': 'Add',
      'common.edit': 'Edit',
      'common.delete': 'Delete',
      'common.cancel': 'Cancel',
      'common.save': 'Save',
      'common.save_edit': 'Save edits',
      'common.save_sheet': 'Save to Sheet',
      'common.close': 'Close',
      'common.photo': 'Photo',
      'common.photo_link': 'Photo (Link URL)',
      'common.name_lao_long': 'Name & Surname (Lao)',
      'common.name_en_long': 'Name & Surname (English)',
      'common.name_lao_th': 'Name & Surname (Lao)',
      'common.name_en_th': 'Name & Surname (EN)',
      'common.position': 'Position',
      'common.subject': 'Subject',
      'common.phone': 'Phone',
      'common.class_room': 'Class/Room',
      'common.manage': 'Manage',
      'common.see_photo': 'Click to view full size',
      'common.all_class': 'All classes',
      'common.room': 'Room',
      'common.saving': 'Saving...',
      'common.no_data': 'No data',

      'dash.title': 'Dashboard',
      'dash.live': 'Live Data',
      'dash.sample': 'Sample Data',
      'dash.stat.students': 'Total Students',
      'dash.stat.teachers': 'Total Teachers',
      'dash.stat.classes': 'Total Classrooms',
      'dash.stat.ann': 'Announcements',
      'dash.urgent': 'Urgent Announcements',
      'dash.normal': 'General Announcements',
      'dash.badge.urgent': 'Urgent',
      'dash.badge.normal': 'General',
      'dash.no_urgent': 'No urgent announcements',
      'dash.no_ann': 'No announcements',
      'dash.past': 'Recent Activities',
      'dash.activity': 'Activity',

      'modal.add_ann': 'Add Announcement / Activity',
      'modal.edit_ann': 'Edit Announcement / Activity',
      'modal.date': 'Date',
      'modal.type': 'Type',
      'modal.title': 'Title',
      'modal.content': 'Content',
      'modal.title_ph': 'Enter announcement title',
      'modal.content_ph': 'Enter announcement content',

      'year.current': 'Current Academic Year',
      'year.active': 'In Progress',
      'year.history': 'All Academic Years',
      'year.start': 'Start Date',
      'year.end': 'End Date',
      'year.status': 'Status',
      'year.note': 'Note',
      'year.empty': 'No academic year data — please add data in the "academic_year" sheet in Google Sheet',
      'year.sheet_info': 'Google Sheet Info',
      'year.sheet_desc': 'Academic year data pulled from Sheet Tab named',
      'year.col_required': 'Required column structure:',
      'year.col_meaning': 'Meaning',
      'year.col_example': 'Example',

      'teach.title_full': 'Teacher Information',
      'teach.search': 'Search name, position, subject...',
      'teach.add': 'Add Teacher',
      'teach.empty': 'No teacher data found',
      'teach.add_title': 'Add Teacher Information',
      'teach.edit_title': 'Edit Teacher Information',

      'stu.title_full': 'Student Information',
      'stu.search': 'Search name, class...',
      'stu.opt_kinder': 'Kindergarten',
      'stu.opt_primary': 'Primary',
      'stu.opt_secondary': 'Secondary',
      'stu.total_label': 'Total Students',
      'stu.total_unit': 'people',
      'stu.empty': 'No student data found',
      'stu.add': 'Add Student',
      'stu.add_title': 'Add Student Information',
      'stu.edit_title': 'Edit Student Information',

      'score.title_full': 'Score System',
      'score.rules': 'Grading Rules',
      'score.view': 'View Scores ›',
      'score.noLink': 'No link yet',
      'score.edit_links': 'Edit Links',
      'score.kinder': 'Kindergarten',
      'score.primary': 'Primary',
      'score.secondary': 'Secondary',
      'score.class1': 'Kindergarten',
      'score.class2': 'Primary',
      'score.class3': 'Secondary',

      'att.title_full': 'Attendance Tracking',
      'att.view': 'View Attendance ›',
      'att.noLink': 'No link yet',
      'att.edit_links': 'Edit Links',

      'sched.title_full': 'Schedule',
      'sched.study': 'Study Schedule (Students)',
      'sched.teach': 'Teaching Schedule (Teachers)',
      'sched.empty': 'No schedule data',
      'sched.break': 'Break',

      'class.title_full': 'All Classes',
      'class.kinder': 'Kindergarten',
      'class.primary': 'Primary',
      'class.secondary': 'Secondary',
      'class.students': 'Students',
      'class.unit': '',
      'class.empty': 'No student data in this class',
      'class.modal_title': 'Students',

      'rules.title': 'Grading Rules',
      'rules.level': 'Level',
      'rules.score': 'Score',
      'rules.meaning': 'Meaning',
      'rules.excellent': 'Excellent',
      'rules.excellent_m': 'Passed with highest honors',
      'rules.good': 'Good',
      'rules.good_m': 'Passed well',
      'rules.average': 'Average',
      'rules.average_m': 'Passed',
      'rules.weak': 'Weak',
      'rules.weak_m': 'Passed (conditional)',
      'rules.fail': 'Fail',
      'rules.fail_m': 'Not passed'
    }
  };

  NT2.Lang = {
    current: 'lo',

    t(key, fallback) {
      const val = dict[this.current] && dict[this.current][key];
      if (val !== undefined && val !== null) return val;
      const lo = dict.lo && dict.lo[key];
      if (lo !== undefined && lo !== null) return lo;
      return (fallback !== undefined) ? fallback : key;
    },

    applyStatic() {
      document.querySelectorAll('[data-i18n]').forEach(el => {
        const txt = this.t(el.getAttribute('data-i18n'));
        if (txt) el.textContent = txt;
      });
      document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const txt = this.t(el.getAttribute('data-i18n-placeholder'));
        if (txt) el.setAttribute('placeholder', txt);
      });
      document.querySelectorAll('[data-i18n-title]').forEach(el => {
        const txt = this.t(el.getAttribute('data-i18n-title'));
        if (txt) el.setAttribute('title', txt);
      });

      const dl = document.getElementById('langLabel');
      if (dl) dl.textContent = this.t('lang.label');
      const yl = document.getElementById('yearDropdownLabel');
      if (yl && !yl.dataset.custom) yl.textContent = this.t('header.year');

      document.documentElement.lang = (this.current === 'en') ? 'en' : 'lo';
    },

    applyLogin() {
      const btn = document.getElementById('loginBtn');
      if (!btn) return;
      const loggedIn = !!(window.NT2 && NT2.Auth && NT2.Auth.isLoggedIn);
      btn.classList.toggle('logged-in', loggedIn);
      btn.innerHTML = loggedIn
        ? `<span class="material-symbols-rounded">logout</span><span>${this.t('login.logout')}</span>`
        : `<span class="material-symbols-rounded">login</span><span>${this.t('login.login')}</span>`;
    },

    apply() {
      this.applyStatic();
      this.applyLogin();
      if (window.NT2 && NT2.App && typeof NT2.App.applyLang === 'function') {
        NT2.App.applyLang();
      }
    },

    set(lang) {
      this.current = (lang === 'en') ? 'en' : 'lo';
      this.apply();
    },

    toggle() {
      this.set(this.current === 'en' ? 'lo' : 'en');
    },

    init() {
      this.current = 'lo';
      this.applyStatic();
    }
  };
})();